---
name: Schema-RDBMS-AUS
version: 0.01
author:
  - 'Tyler "Crackerjack" MacDonald <japh@crackerjack.net>'
abstract: 'Authentication, Users and Sessions in an SQL schema'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Session: 4.03
  Class::Driver: 0.002
  DBIx::Migration::Directories: 0.01
  DBIx::Transaction: 0.005
build_requires:
  Module::Build: 0.27_03
  Test::CPANpm: 0.008
  Test::Exception: 0.21
provides:
  CGI::Session::AUS:
    file: lib/CGI/Session/AUS.pm
  CGI::Session::Driver::aus:
    file: lib/CGI/Session/Driver/aus.pm
  CGI::Session::Driver::aus::Pg:
    file: lib/CGI/Session/Driver/aus/Pg.pm
  Schema::RDBMS::AUS:
    file: lib/Schema/RDBMS/AUS.pm
    version: 0.01
  Schema::RDBMS::AUS::Crypt::MD5:
    file: lib/Schema/RDBMS/AUS/Crypt/MD5.pm
  Schema::RDBMS::AUS::Crypt::None:
    file: lib/Schema/RDBMS/AUS/Crypt/None.pm
  Schema::RDBMS::AUS::Crypt::SHA1:
    file: lib/Schema/RDBMS/AUS/Crypt/SHA1.pm
  Schema::RDBMS::AUS::User:
    file: lib/Schema/RDBMS/AUS/User.pm
generated_by: Module::Build version 0.2706
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
